---
title: "Estimating the Unobserved: A Simulation Study on Censoring and Truncation in Evidence Accumulation Models"
# If blank, the running header is the title in upper case.
shorttitle: "Censoring and Truncation in EAM"
# Set names and affiliations.
# It is nice to specify everyone's orcid, if possible.
# There can be only one corresponding author, but declaring one is optional.
author:
  - name: Jeroen E. Timmerman
    corresponding: true
    orcid: 0009-0003-8208-0509
    email: j.e.timmerman@uva.nl
    affiliations:
      - name: "University of Amsterdam"
        group: Psychological Methods
        department: Department of Psychology
        address: Nieuwe Achtergracht129-B
        city: Amsterdam
        country: the Netherlands
        postal-code: 1018 WS
    conflict-of-interest: The authors have no conflicts of interest to disclose.
abstract: "This is a placeholder for the abstract."
# Put as many keywords at you like, separated by commmas (e.g., [reliability, validity, generalizability])
keywords: [censoring, truncation, missing data, evidence accumulation, choice response data, diffusion decision model, linear ballistic accumulator, Bayesian hierarchical modeling]
# If true, tables and figures are mingled with the text instead of listed at the end of the document.
course: "MI2324RM: Research Master's Internship"
professor: Andrew Heathcote
duedate: August 31st, 2024
floatsintext: true
# Numbered lines (.pdf and .docx only)
numbered-lines: false
# File with references
bibliography: references.bib
# Suppress title page
suppress-title-page: false
# Link citations to references
link-citations: true
format:
  apaquarto-docx: default
  html: default
  apaquarto-pdf:
    documentmode: stu
---

::: {.content-visible when-format="html"}

# Introduction

:::

This is my introductory paragraph. The title will be placed above it automatically. *Do not start with an introductory heading* (e.g., "Introduction"). The title acts as your Level 1 heading for the introduction [@schneider2015intelligence].


# Method

General remarks on method. This paragraph is optional.

Not all papers require each of these sections. Edit them as needed. Consult the [Journal Article Reporting Standards](https://apastyle.apa.org/jars) for what is needed for your type of article.

## Participants

Who are they? How were they recruited? Report criteria for participant inclusion and exclusion. Perhaps some basic demographic stats are in order. A table is a great way to avoid repetition in statistical reporting.

## Measures

This section can also be titled **Materials** or **Apparatus**. Whatever tools, equipment, or measurement devices used in the study should be described.

## Procedure

What did participants do? How are the data going to be analyzed?

# Results

## Descriptive Statistics

Describe the basic characteristics of the primary variables. My ideal is to describe the variables well enough that someone conducting a meta-analysis can include the study without needing to ask for additional information.

# Discussion

Describe results in non-statistical terms. <!-- Add sections as needed. -->

## Limitations and Future Directions

Every study has limitations. Based on this study, some additional steps might include...

## Conclusion

Describe the main point of the paper.

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::

# Appendix

# The Title for Appendix


